const sqlite3 = require("sqlite3").verbose();
const path = require("path");
const db = new sqlite3.Database(path.join(__dirname, "sqlite.db"));

// Product data with 40+ items per animal
const products = [
  // DOGS - Food & Treats (15 items)
  {
    name: "Premium Dog Food - Chicken & Rice",
    animal: "Dogs",
    category: "Food & Treats",
    price: 4500,
    image: "🐕",
    stock: 50,
    rating: 4.8,
  },
  {
    name: "Grain-Free Dog Food - Salmon",
    animal: "Dogs",
    category: "Food & Treats",
    price: 5200,
    image: "🐕",
    stock: 45,
    rating: 4.9,
  },
  {
    name: "Puppy Food - Lamb & Vegetables",
    animal: "Dogs",
    category: "Food & Treats",
    price: 4800,
    image: "🐕",
    stock: 60,
    rating: 4.7,
  },
  {
    name: "Senior Dog Food - Joint Support",
    animal: "Dogs",
    category: "Food & Treats",
    price: 4900,
    image: "🐕",
    stock: 40,
    rating: 4.6,
  },
  {
    name: "Dog Treats - Training Bites",
    animal: "Dogs",
    category: "Food & Treats",
    price: 1200,
    image: "🦴",
    stock: 80,
    rating: 4.5,
  },
  {
    name: "Dental Chews - Fresh Breath",
    animal: "Dogs",
    category: "Food & Treats",
    price: 1800,
    image: "🦷",
    stock: 70,
    rating: 4.7,
  },
  {
    name: "Rawhide Bones - Large",
    animal: "Dogs",
    category: "Food & Treats",
    price: 2500,
    image: "🦴",
    stock: 55,
    rating: 4.4,
  },
  {
    name: "Freeze-Dried Dog Treats",
    animal: "Dogs",
    category: "Food & Treats",
    price: 3200,
    image: "🍖",
    stock: 50,
    rating: 4.8,
  },
  {
    name: "Wet Dog Food - Beef Stew",
    animal: "Dogs",
    category: "Food & Treats",
    price: 1500,
    image: "🥫",
    stock: 65,
    rating: 4.6,
  },
  {
    name: "Dog Biscuits - Natural",
    animal: "Dogs",
    category: "Food & Treats",
    price: 2000,
    image: "🍪",
    stock: 75,
    rating: 4.5,
  },
  {
    name: "Puppy Training Treats",
    animal: "Dogs",
    category: "Food & Treats",
    price: 1400,
    image: "🎯",
    stock: 90,
    rating: 4.7,
  },
  {
    name: "Weight Management Dog Food",
    animal: "Dogs",
    category: "Food & Treats",
    price: 5100,
    image: "⚖️",
    stock: 35,
    rating: 4.6,
  },
  {
    name: "Hypoallergenic Dog Food",
    animal: "Dogs",
    category: "Food & Treats",
    price: 5800,
    image: "🌾",
    stock: 30,
    rating: 4.9,
  },
  {
    name: "Dog Jerky Treats - Chicken",
    animal: "Dogs",
    category: "Food & Treats",
    price: 2800,
    image: "🍗",
    stock: 60,
    rating: 4.5,
  },
  {
    name: "Puppy Milk Replacer",
    animal: "Dogs",
    category: "Food & Treats",
    price: 3500,
    image: "🥛",
    stock: 25,
    rating: 4.8,
  },

  // DOGS - Toys & Accessories (15 items)
  {
    name: "Tennis Ball - Pack of 3",
    animal: "Dogs",
    category: "Toys & Accessories",
    price: 800,
    image: "🎾",
    stock: 100,
    rating: 4.6,
  },
  {
    name: "Rope Tug Toy - Durable",
    animal: "Dogs",
    category: "Toys & Accessories",
    price: 1200,
    image: "🪢",
    stock: 85,
    rating: 4.7,
  },
  {
    name: "Interactive Puzzle Toy",
    animal: "Dogs",
    category: "Toys & Accessories",
    price: 3500,
    image: "🧩",
    stock: 40,
    rating: 4.8,
  },
  {
    name: "Frisbee - Flying Disc",
    animal: "Dogs",
    category: "Toys & Accessories",
    price: 1500,
    image: "🥏",
    stock: 70,
    rating: 4.5,
  },
  {
    name: "Kong Classic Dog Toy",
    animal: "Dogs",
    category: "Toys & Accessories",
    price: 2800,
    image: "🔴",
    stock: 55,
    rating: 4.9,
  },
  {
    name: "Plush Squeaky Toy",
    animal: "Dogs",
    category: "Toys & Accessories",
    price: 1800,
    image: "🧸",
    stock: 90,
    rating: 4.4,
  },
  {
    name: "Dog Leash - Nylon 6ft",
    animal: "Dogs",
    category: "Toys & Accessories",
    price: 2000,
    image: "🦮",
    stock: 75,
    rating: 4.6,
  },
  {
    name: "Retractable Dog Leash",
    animal: "Dogs",
    category: "Toys & Accessories",
    price: 4500,
    image: "🦮",
    stock: 50,
    rating: 4.7,
  },
  {
    name: "Dog Collar - Adjustable",
    animal: "Dogs",
    category: "Toys & Accessories",
    price: 1500,
    image: "⭕",
    stock: 95,
    rating: 4.5,
  },
  {
    name: "Dog Harness - No Pull",
    animal: "Dogs",
    category: "Toys & Accessories",
    price: 3800,
    image: "🎽",
    stock: 45,
    rating: 4.8,
  },
  {
    name: "Dog Bed - Orthopedic",
    animal: "Dogs",
    category: "Toys & Accessories",
    price: 8500,
    image: "🛏️",
    stock: 30,
    rating: 4.9,
  },
  {
    name: "Dog Crate - Large",
    animal: "Dogs",
    category: "Toys & Accessories",
    price: 12000,
    image: "📦",
    stock: 20,
    rating: 4.7,
  },
  {
    name: "Dog Bowl Set - Stainless Steel",
    animal: "Dogs",
    category: "Toys & Accessories",
    price: 2500,
    image: "🥣",
    stock: 60,
    rating: 4.6,
  },
  {
    name: "Slow Feeder Bowl",
    animal: "Dogs",
    category: "Toys & Accessories",
    price: 3200,
    image: "🍽️",
    stock: 40,
    rating: 4.8,
  },
  {
    name: "Dog ID Tag - Engraved",
    animal: "Dogs",
    category: "Toys & Accessories",
    price: 800,
    image: "🏷️",
    stock: 100,
    rating: 4.5,
  },

  // DOGS - Health & Grooming (10 items)
  {
    name: "Dog Shampoo - Oatmeal",
    animal: "Dogs",
    category: "Health & Grooming",
    price: 2200,
    image: "🧴",
    stock: 70,
    rating: 4.7,
  },
  {
    name: "Dog Brush - Slicker",
    animal: "Dogs",
    category: "Health & Grooming",
    price: 1500,
    image: "🪮",
    stock: 80,
    rating: 4.6,
  },
  {
    name: "Nail Clippers - Professional",
    animal: "Dogs",
    category: "Health & Grooming",
    price: 1800,
    image: "✂️",
    stock: 65,
    rating: 4.5,
  },
  {
    name: "Ear Cleaner Solution",
    animal: "Dogs",
    category: "Health & Grooming",
    price: 1400,
    image: "👂",
    stock: 75,
    rating: 4.6,
  },
  {
    name: "Toothbrush & Toothpaste Set",
    animal: "Dogs",
    category: "Health & Grooming",
    price: 2500,
    image: "🪥",
    stock: 60,
    rating: 4.8,
  },
  {
    name: "Flea & Tick Treatment",
    animal: "Dogs",
    category: "Health & Grooming",
    price: 4500,
    image: "🦟",
    stock: 50,
    rating: 4.7,
  },
  {
    name: "Dog Vitamins - Multivitamin",
    animal: "Dogs",
    category: "Health & Grooming",
    price: 3800,
    image: "💊",
    stock: 45,
    rating: 4.6,
  },
  {
    name: "Joint Supplements - Glucosamine",
    animal: "Dogs",
    category: "Health & Grooming",
    price: 5200,
    image: "💊",
    stock: 35,
    rating: 4.9,
  },
  {
    name: "Grooming Wipes - 100ct",
    animal: "Dogs",
    category: "Health & Grooming",
    price: 1800,
    image: "🧻",
    stock: 85,
    rating: 4.5,
  },
  {
    name: "Deodorizing Spray",
    animal: "Dogs",
    category: "Health & Grooming",
    price: 1600,
    image: "💨",
    stock: 70,
    rating: 4.4,
  },

  // CATS - Food & Treats (15 items)
  {
    name: "Premium Cat Food - Tuna & Salmon",
    animal: "Cats",
    category: "Food & Treats",
    price: 4200,
    image: "🐱",
    stock: 55,
    rating: 4.8,
  },
  {
    name: "Grain-Free Cat Food - Chicken",
    animal: "Cats",
    category: "Food & Treats",
    price: 4800,
    image: "🐱",
    stock: 50,
    rating: 4.9,
  },
  {
    name: "Kitten Food - Chicken & Liver",
    animal: "Cats",
    category: "Food & Treats",
    price: 4500,
    image: "🐱",
    stock: 65,
    rating: 4.7,
  },
  {
    name: "Senior Cat Food - Weight Control",
    animal: "Cats",
    category: "Food & Treats",
    price: 4400,
    image: "🐱",
    stock: 40,
    rating: 4.6,
  },
  {
    name: "Cat Treats - Tuna Flavor",
    animal: "Cats",
    category: "Food & Treats",
    price: 1100,
    image: "🐟",
    stock: 90,
    rating: 4.5,
  },
  {
    name: "Dental Cat Treats",
    animal: "Cats",
    category: "Food & Treats",
    price: 1500,
    image: "🦷",
    stock: 75,
    rating: 4.7,
  },
  {
    name: "Catnip - Organic",
    animal: "Cats",
    category: "Food & Treats",
    price: 800,
    image: "🌿",
    stock: 100,
    rating: 4.6,
  },
  {
    name: "Freeze-Dried Cat Treats",
    animal: "Cats",
    category: "Food & Treats",
    price: 2800,
    image: "🍖",
    stock: 60,
    rating: 4.8,
  },
  {
    name: "Wet Cat Food - Chicken Pate",
    animal: "Cats",
    category: "Food & Treats",
    price: 1200,
    image: "🥫",
    stock: 80,
    rating: 4.6,
  },
  {
    name: "Cat Food - Indoor Formula",
    animal: "Cats",
    category: "Food & Treats",
    price: 4600,
    image: "🏠",
    stock: 45,
    rating: 4.7,
  },
  {
    name: "Hairball Control Cat Food",
    animal: "Cats",
    category: "Food & Treats",
    price: 4900,
    image: "🧶",
    stock: 35,
    rating: 4.8,
  },
  {
    name: "Hypoallergenic Cat Food",
    animal: "Cats",
    category: "Food & Treats",
    price: 5500,
    image: "🌾",
    stock: 30,
    rating: 4.9,
  },
  {
    name: "Cat Jerky Treats - Salmon",
    animal: "Cats",
    category: "Food & Treats",
    price: 2500,
    image: "🍗",
    stock: 70,
    rating: 4.5,
  },
  {
    name: "Kitten Milk Replacer",
    animal: "Cats",
    category: "Food & Treats",
    price: 3200,
    image: "🥛",
    stock: 25,
    rating: 4.8,
  },
  {
    name: "Cat Food - Urinary Health",
    animal: "Cats",
    category: "Food & Treats",
    price: 5100,
    image: "💧",
    stock: 40,
    rating: 4.7,
  },

  // CATS - Toys & Accessories (15 items)
  {
    name: "Cat Wand Toy - Feather",
    animal: "Cats",
    category: "Toys & Accessories",
    price: 1200,
    image: "🪶",
    stock: 95,
    rating: 4.7,
  },
  {
    name: "Laser Pointer - Red Dot",
    animal: "Cats",
    category: "Toys & Accessories",
    price: 1500,
    image: "🔴",
    stock: 85,
    rating: 4.6,
  },
  {
    name: "Interactive Cat Puzzle",
    animal: "Cats",
    category: "Toys & Accessories",
    price: 3200,
    image: "🧩",
    stock: 50,
    rating: 4.8,
  },
  {
    name: "Catnip Mouse Toy",
    animal: "Cats",
    category: "Toys & Accessories",
    price: 800,
    image: "🐭",
    stock: 100,
    rating: 4.5,
  },
  {
    name: "Scratching Post - Tall",
    animal: "Cats",
    category: "Toys & Accessories",
    price: 6500,
    image: "🌳",
    stock: 30,
    rating: 4.9,
  },
  {
    name: "Cat Tree - Multi-Level",
    animal: "Cats",
    category: "Toys & Accessories",
    price: 15000,
    image: "🌲",
    stock: 15,
    rating: 4.8,
  },
  {
    name: "Cat Collar - Breakaway",
    animal: "Cats",
    category: "Toys & Accessories",
    price: 1200,
    image: "⭕",
    stock: 90,
    rating: 4.6,
  },
  {
    name: "Cat Harness & Leash Set",
    animal: "Cats",
    category: "Toys & Accessories",
    price: 3500,
    image: "🎽",
    stock: 55,
    rating: 4.7,
  },
  {
    name: "Cat Bed - Cozy Cave",
    animal: "Cats",
    category: "Toys & Accessories",
    price: 4500,
    image: "🛏️",
    stock: 45,
    rating: 4.8,
  },
  {
    name: "Cat Carrier - Soft Sided",
    animal: "Cats",
    category: "Toys & Accessories",
    price: 5500,
    image: "📦",
    stock: 35,
    rating: 4.7,
  },
  {
    name: "Cat Bowl Set - Ceramic",
    animal: "Cats",
    category: "Toys & Accessories",
    price: 2200,
    image: "🥣",
    stock: 70,
    rating: 4.6,
  },
  {
    name: "Automatic Cat Feeder",
    animal: "Cats",
    category: "Toys & Accessories",
    price: 12000,
    image: "🤖",
    stock: 20,
    rating: 4.9,
  },
  {
    name: "Water Fountain - Cat",
    animal: "Cats",
    category: "Toys & Accessories",
    price: 8500,
    image: "⛲",
    stock: 25,
    rating: 4.8,
  },
  {
    name: "Litter Box - Covered",
    animal: "Cats",
    category: "Toys & Accessories",
    price: 4500,
    image: "🚽",
    stock: 40,
    rating: 4.7,
  },
  {
    name: "Cat ID Tag - Engraved",
    animal: "Cats",
    category: "Toys & Accessories",
    price: 800,
    image: "🏷️",
    stock: 100,
    rating: 4.5,
  },

  // CATS - Health & Grooming (10 items)
  {
    name: "Cat Shampoo - Hypoallergenic",
    animal: "Cats",
    category: "Health & Grooming",
    price: 2000,
    image: "🧴",
    stock: 75,
    rating: 4.7,
  },
  {
    name: "Cat Brush - Slicker",
    animal: "Cats",
    category: "Health & Grooming",
    price: 1400,
    image: "🪮",
    stock: 85,
    rating: 4.6,
  },
  {
    name: "Nail Clippers - Cat",
    animal: "Cats",
    category: "Health & Grooming",
    price: 1600,
    image: "✂️",
    stock: 70,
    rating: 4.5,
  },
  {
    name: "Ear Cleaner - Cat",
    animal: "Cats",
    category: "Health & Grooming",
    price: 1300,
    image: "👂",
    stock: 80,
    rating: 4.6,
  },
  {
    name: "Toothbrush Set - Cat",
    animal: "Cats",
    category: "Health & Grooming",
    price: 2300,
    image: "🪥",
    stock: 65,
    rating: 4.8,
  },
  {
    name: "Flea Treatment - Spot On",
    animal: "Cats",
    category: "Health & Grooming",
    price: 4200,
    image: "🦟",
    stock: 55,
    rating: 4.7,
  },
  {
    name: "Cat Vitamins - Multivitamin",
    animal: "Cats",
    category: "Health & Grooming",
    price: 3500,
    image: "💊",
    stock: 50,
    rating: 4.6,
  },
  {
    name: "Hairball Remedy - Gel",
    animal: "Cats",
    category: "Health & Grooming",
    price: 2800,
    image: "🧶",
    stock: 60,
    rating: 4.8,
  },
  {
    name: "Grooming Wipes - Cat",
    animal: "Cats",
    category: "Health & Grooming",
    price: 1700,
    image: "🧻",
    stock: 90,
    rating: 4.5,
  },
  {
    name: "Deodorizing Spray - Cat",
    animal: "Cats",
    category: "Health & Grooming",
    price: 1500,
    image: "💨",
    stock: 75,
    rating: 4.4,
  },

  // BIRDS - Food & Treats (15 items)
  {
    name: "Premium Bird Seed Mix",
    animal: "Birds",
    category: "Food & Treats",
    price: 1800,
    image: "🐦",
    stock: 80,
    rating: 4.7,
  },
  {
    name: "Parrot Pellets - Complete",
    animal: "Birds",
    category: "Food & Treats",
    price: 3200,
    image: "🦜",
    stock: 60,
    rating: 4.8,
  },
  {
    name: "Canary Food - Premium Blend",
    animal: "Birds",
    category: "Food & Treats",
    price: 1500,
    image: "🐤",
    stock: 70,
    rating: 4.6,
  },
  {
    name: "Cockatiel Food - Fortified",
    animal: "Birds",
    category: "Food & Treats",
    price: 2800,
    image: "🦜",
    stock: 55,
    rating: 4.7,
  },
  {
    name: "Bird Treats - Millet Spray",
    animal: "Birds",
    category: "Food & Treats",
    price: 800,
    image: "🌾",
    stock: 100,
    rating: 4.5,
  },
  {
    name: "Honey Sticks - Bird Treats",
    animal: "Birds",
    category: "Food & Treats",
    price: 1200,
    image: "🍯",
    stock: 90,
    rating: 4.6,
  },
  {
    name: "Fruit Treats - Dried",
    animal: "Birds",
    category: "Food & Treats",
    price: 2000,
    image: "🍎",
    stock: 75,
    rating: 4.7,
  },
  {
    name: "Nut Mix - For Birds",
    animal: "Birds",
    category: "Food & Treats",
    price: 3500,
    image: "🥜",
    stock: 50,
    rating: 4.8,
  },
  {
    name: "Cuttlebone - Calcium",
    animal: "Birds",
    category: "Food & Treats",
    price: 600,
    image: "🦴",
    stock: 95,
    rating: 4.5,
  },
  {
    name: "Bird Vitamins - Liquid",
    animal: "Birds",
    category: "Food & Treats",
    price: 2800,
    image: "💊",
    stock: 65,
    rating: 4.7,
  },
  {
    name: "Probiotic Bird Food",
    animal: "Birds",
    category: "Food & Treats",
    price: 3800,
    image: "🦠",
    stock: 45,
    rating: 4.8,
  },
  {
    name: "Organic Bird Seed",
    animal: "Birds",
    category: "Food & Treats",
    price: 4200,
    image: "🌾",
    stock: 40,
    rating: 4.9,
  },
  {
    name: "Baby Bird Formula",
    animal: "Birds",
    category: "Food & Treats",
    price: 4500,
    image: "🍼",
    stock: 30,
    rating: 4.8,
  },
  {
    name: "Grit - Digestive Aid",
    animal: "Birds",
    category: "Food & Treats",
    price: 1000,
    image: "🪨",
    stock: 85,
    rating: 4.6,
  },
  {
    name: "Nectar - For Hummingbirds",
    animal: "Birds",
    category: "Food & Treats",
    price: 1500,
    image: "🍯",
    stock: 70,
    rating: 4.7,
  },

  // BIRDS - Toys & Accessories (15 items)
  {
    name: "Bird Perch - Natural Wood",
    animal: "Birds",
    category: "Toys & Accessories",
    price: 1800,
    image: "🌿",
    stock: 80,
    rating: 4.7,
  },
  {
    name: "Swing - For Birds",
    animal: "Birds",
    category: "Toys & Accessories",
    price: 1200,
    image: "🪑",
    stock: 90,
    rating: 4.6,
  },
  {
    name: "Bird Mirror - Safe",
    animal: "Birds",
    category: "Toys & Accessories",
    price: 1500,
    image: "🪞",
    stock: 85,
    rating: 4.5,
  },
  {
    name: "Bird Bell Toy",
    animal: "Birds",
    category: "Toys & Accessories",
    price: 1000,
    image: "🔔",
    stock: 95,
    rating: 4.6,
  },
  {
    name: "Ladder - Bird Toy",
    animal: "Birds",
    category: "Toys & Accessories",
    price: 800,
    image: "🪜",
    stock: 100,
    rating: 4.5,
  },
  {
    name: "Bird Cage - Large",
    animal: "Birds",
    category: "Toys & Accessories",
    price: 18000,
    image: "🏠",
    stock: 15,
    rating: 4.9,
  },
  {
    name: "Bird Cage - Medium",
    animal: "Birds",
    category: "Toys & Accessories",
    price: 12000,
    image: "🏠",
    stock: 25,
    rating: 4.8,
  },
  {
    name: "Bird Cage - Small",
    animal: "Birds",
    category: "Toys & Accessories",
    price: 8500,
    image: "🏠",
    stock: 35,
    rating: 4.7,
  },
  {
    name: "Food Dish - Bird",
    animal: "Birds",
    category: "Toys & Accessories",
    price: 800,
    image: "🥣",
    stock: 100,
    rating: 4.5,
  },
  {
    name: "Water Dispenser - Bird",
    animal: "Birds",
    category: "Toys & Accessories",
    price: 1200,
    image: "💧",
    stock: 90,
    rating: 4.6,
  },
  {
    name: "Bird Bath - Hanging",
    animal: "Birds",
    category: "Toys & Accessories",
    price: 2500,
    image: "🛁",
    stock: 60,
    rating: 4.7,
  },
  {
    name: "Cage Cover - Dark",
    animal: "Birds",
    category: "Toys & Accessories",
    price: 1800,
    image: "🌙",
    stock: 70,
    rating: 4.6,
  },
  {
    name: "Play Gym - For Birds",
    animal: "Birds",
    category: "Toys & Accessories",
    price: 5500,
    image: "🎪",
    stock: 30,
    rating: 4.8,
  },
  {
    name: "Shredding Toy - Paper",
    animal: "Birds",
    category: "Toys & Accessories",
    price: 1000,
    image: "📄",
    stock: 85,
    rating: 4.5,
  },
  {
    name: "Foraging Toy - Puzzle",
    animal: "Birds",
    category: "Toys & Accessories",
    price: 3200,
    image: "🧩",
    stock: 50,
    rating: 4.7,
  },

  // BIRDS - Health & Grooming (10 items)
  {
    name: "Bird Mite Spray",
    animal: "Birds",
    category: "Health & Grooming",
    price: 2200,
    image: "🦟",
    stock: 65,
    rating: 4.7,
  },
  {
    name: "Cage Cleaner - Disinfectant",
    animal: "Birds",
    category: "Health & Grooming",
    price: 1800,
    image: "🧴",
    stock: 75,
    rating: 4.6,
  },
  {
    name: "Perch Cleaner",
    animal: "Birds",
    category: "Health & Grooming",
    price: 1200,
    image: "🧽",
    stock: 80,
    rating: 4.5,
  },
  {
    name: "Bird Vitamins - Powder",
    animal: "Birds",
    category: "Health & Grooming",
    price: 2800,
    image: "💊",
    stock: 60,
    rating: 4.7,
  },
  {
    name: "Calcium Supplement - Birds",
    animal: "Birds",
    category: "Health & Grooming",
    price: 2000,
    image: "🦴",
    stock: 70,
    rating: 4.6,
  },
  {
    name: "Probiotic - For Birds",
    animal: "Birds",
    category: "Health & Grooming",
    price: 3200,
    image: "🦠",
    stock: 55,
    rating: 4.8,
  },
  {
    name: "Feather Conditioner",
    animal: "Birds",
    category: "Health & Grooming",
    price: 2500,
    image: "🪶",
    stock: 65,
    rating: 4.7,
  },
  {
    name: "Beak Conditioner",
    animal: "Birds",
    category: "Health & Grooming",
    price: 1800,
    image: "🦜",
    stock: 75,
    rating: 4.6,
  },
  {
    name: "Nail Trimmer - Bird",
    animal: "Birds",
    category: "Health & Grooming",
    price: 1500,
    image: "✂️",
    stock: 70,
    rating: 4.5,
  },
  {
    name: "First Aid Kit - Bird",
    animal: "Birds",
    category: "Health & Grooming",
    price: 4500,
    image: "🏥",
    stock: 40,
    rating: 4.8,
  },
];

// Users with different roles
const users = [
  {
    email: "superadmin@petmart.ng",
    password: "super123",
    name: "Super Admin",
    role: "superadmin",
  },
  {
    email: "admin@petmart.ng",
    password: "admin123",
    name: "Admin User",
    role: "admin",
  },
  {
    email: "customer@petmart.ng",
    password: "customer123",
    name: "Customer User",
    role: "customer",
  },
];

// Initialize database
db.serialize(() => {
  // Drop existing tables
  db.run("DROP TABLE IF EXISTS products");
  db.run("DROP TABLE IF EXISTS users");
  db.run("DROP TABLE IF EXISTS orders");
  db.run("DROP TABLE IF EXISTS activity_log");

  // Create tables with updated schema
  db.run(`
    CREATE TABLE users (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      email TEXT NOT NULL UNIQUE,
      password TEXT NOT NULL,
      name TEXT NOT NULL,
      role TEXT NOT NULL
    )
  `);

  db.run(`
    CREATE TABLE products (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL,
      animal TEXT NOT NULL,
      category TEXT NOT NULL,
      price INTEGER NOT NULL,
      image TEXT NOT NULL,
      stock INTEGER NOT NULL,
      rating REAL NOT NULL
    )
  `);

  db.run(`
    CREATE TABLE orders (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      customerId INTEGER NOT NULL,
      customerName TEXT NOT NULL,
      total INTEGER NOT NULL,
      status TEXT NOT NULL,
      date TEXT NOT NULL,
      FOREIGN KEY (customerId) REFERENCES users (id)
    )
  `);

  db.run(`
    CREATE TABLE activity_log (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      userId INTEGER,
      action TEXT NOT NULL,
      timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (userId) REFERENCES users (id)
    )
  `);

  // Insert users
  const userStmt = db.prepare(
    "INSERT INTO users (email, password, name, role) VALUES (?, ?, ?, ?)"
  );
  users.forEach((user) => {
    userStmt.run(user.email, user.password, user.name, user.role);
  });
  userStmt.finalize();

  // Insert products
  const productStmt = db.prepare(
    "INSERT INTO products (name, animal, category, price, image, stock, rating) VALUES (?, ?, ?, ?, ?, ?, ?)"
  );
  products.forEach((product) => {
    productStmt.run(
      product.name,
      product.animal,
      product.category,
      product.price,
      product.image,
      product.stock,
      product.rating
    );
  });
  productStmt.finalize();

  console.log(`✅ Database seeded successfully!`);
  console.log(`   - ${users.length} users created`);
  console.log(`   - ${products.length} products created`);
  console.log(
    `   - Dogs: ${products.filter((p) => p.animal === "Dogs").length} products`
  );
  console.log(
    `   - Cats: ${products.filter((p) => p.animal === "Cats").length} products`
  );
  console.log(
    `   - Birds: ${
      products.filter((p) => p.animal === "Birds").length
    } products`
  );

  db.close((err) => {
    if (err) {
      console.error("Error closing database:", err.message);
    } else {
      console.log("Database connection closed.");
    }
    process.exit(0);
  });
});
